/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.Random;


/**
 *
 * @author Luis Ugas
 */
public class ventana1 extends javax.swing.JFrame {
 
//    ventana0 cont= new ventana0();
    
private int reguladob;
 
public double totalg;
public int totalvendidos;
public int medvendidos;
public int medreguladosvendidos;
public int mednoreguladosvendidos;
public int utilesvendidos;
public double totalgeneralvendido;
public double totalmedvendido;
public double totalutilesvendido;
public int totalclientes;
private String cicliente;
Random rnd = new Random();
    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();
        setLocationRelativeTo(null);
        
        jFormattedTextcedula.requestFocus();
        reguladob =0;
//        totalg =0;
//        totalvendidos=0;
//        medvendidos=0;
//        medreguladosvendidos=0;
//        mednoreguladosvendidos=0;
//        utilesvendidos=0;
//        totalgeneralvendido=0;
//        totalmedvendido=0;
//        totalutilesvendido=0;
//        totalclientes=0;
        cicliente="";
         
         
         labelnfactura.setText(""+rnd.nextInt());
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        regulado = new javax.swing.ButtonGroup();
        producto = new javax.swing.ButtonGroup();
        labelnombrefarmacia = new javax.swing.JLabel();
        labelcliente = new javax.swing.JLabel();
        labelcedula = new javax.swing.JLabel();
        jFormattedTextcedula = new javax.swing.JFormattedTextField();
        labelnombres = new javax.swing.JLabel();
        textnombre = new javax.swing.JTextField();
        labelapellidos = new javax.swing.JLabel();
        textapellidos = new javax.swing.JTextField();
        jRadioBmedicamentos = new javax.swing.JRadioButton();
        jRadioButiles = new javax.swing.JRadioButton();
        labelproducto = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        textcodigo = new javax.swing.JTextField();
        labeldescripcion = new javax.swing.JLabel();
        textdescripcion = new javax.swing.JTextField();
        labelcantidad = new javax.swing.JLabel();
        jFormattedTextcantidad = new javax.swing.JFormattedTextField();
        labelcosto = new javax.swing.JLabel();
        jFormattedTextcosto = new javax.swing.JFormattedTextField();
        labelfechaexp = new javax.swing.JLabel();
        jFormattedTextfecha = new javax.swing.JFormattedTextField();
        labelproveedor = new javax.swing.JLabel();
        textproveedor = new javax.swing.JTextField();
        jRadioBregulado = new javax.swing.JRadioButton();
        jRadioBnoregulado1 = new javax.swing.JRadioButton();
        jButtonregistrar = new javax.swing.JButton();
        jButtonnuevoclient = new javax.swing.JButton();
        jButtonfinalizar = new javax.swing.JButton();
        labeltotal = new javax.swing.JLabel();
        jFormattedTexttotal = new javax.swing.JFormattedTextField();
        labeltotalgeneral = new javax.swing.JLabel();
        jFormattedTexttotalgeneral = new javax.swing.JFormattedTextField();
        labelnfactura = new javax.swing.JLabel();
        labelnfacturalbl = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(390, 640));
        setMinimumSize(new java.awt.Dimension(390, 640));
        setPreferredSize(new java.awt.Dimension(390, 640));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelnombrefarmacia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelnombrefarmacia.setText("Farmacia IUPSM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 436;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 26);
        getContentPane().add(labelnombrefarmacia, gridBagConstraints);

        labelcliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelcliente.setForeground(new java.awt.Color(0, 102, 204));
        labelcliente.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        getContentPane().add(labelcliente, gridBagConstraints);

        labelcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcedula.setText("Cédula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 0);
        getContentPane().add(labelcedula, gridBagConstraints);

        jFormattedTextcedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextcedulaFocusLost(evt);
            }
        });
        jFormattedTextcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextcedulaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 272;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        getContentPane().add(jFormattedTextcedula, gridBagConstraints);

        labelnombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnombres.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        getContentPane().add(labelnombres, gridBagConstraints);

        textnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnombreKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 272;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(textnombre, gridBagConstraints);

        labelapellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelapellidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        getContentPane().add(labelapellidos, gridBagConstraints);

        textapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textapellidosKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 272;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(textapellidos, gridBagConstraints);

        producto.add(jRadioBmedicamentos);
        jRadioBmedicamentos.setSelected(true);
        jRadioBmedicamentos.setText("Medicamentos");
        jRadioBmedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBmedicamentosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 27, 0, 0);
        getContentPane().add(jRadioBmedicamentos, gridBagConstraints);

        producto.add(jRadioButiles);
        jRadioButiles.setText("Útiles");
        jRadioButiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButilesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        getContentPane().add(jRadioButiles, gridBagConstraints);

        labelproducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelproducto.setForeground(new java.awt.Color(0, 102, 204));
        labelproducto.setText("Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 0);
        getContentPane().add(labelproducto, gridBagConstraints);

        labelcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcodigo.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 0, 0);
        getContentPane().add(labelcodigo, gridBagConstraints);

        textcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textcodigoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 197;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        getContentPane().add(textcodigo, gridBagConstraints);

        labeldescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeldescripcion.setText("Descripcion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 0, 0);
        getContentPane().add(labeldescripcion, gridBagConstraints);

        textdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textdescripcionKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 197;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        getContentPane().add(textdescripcion, gridBagConstraints);

        labelcantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcantidad.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 0, 0);
        getContentPane().add(labelcantidad, gridBagConstraints);

        jFormattedTextcantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextcantidadKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 197;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        getContentPane().add(jFormattedTextcantidad, gridBagConstraints);

        labelcosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcosto.setText("Costo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 0, 0);
        getContentPane().add(labelcosto, gridBagConstraints);

        jFormattedTextcosto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 197;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        getContentPane().add(jFormattedTextcosto, gridBagConstraints);

        labelfechaexp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelfechaexp.setText("Fecha expedición:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 30, 0, 0);
        getContentPane().add(labelfechaexp, gridBagConstraints);

        jFormattedTextfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextfecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextfechaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 100;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        getContentPane().add(jFormattedTextfecha, gridBagConstraints);

        labelproveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelproveedor.setText("Proveedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 30, 0, 0);
        getContentPane().add(labelproveedor, gridBagConstraints);

        textproveedor.setEditable(false);
        textproveedor.setBackground(new java.awt.Color(204, 204, 204));
        textproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textproveedorKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 100;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 0, 0);
        getContentPane().add(textproveedor, gridBagConstraints);

        regulado.add(jRadioBregulado);
        jRadioBregulado.setText("Regulado");
        jRadioBregulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBreguladoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 11, 0, 0);
        getContentPane().add(jRadioBregulado, gridBagConstraints);

        regulado.add(jRadioBnoregulado1);
        jRadioBnoregulado1.setSelected(true);
        jRadioBnoregulado1.setText("No regulado");
        jRadioBnoregulado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBnoregulado1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 30, 0, 0);
        getContentPane().add(jRadioBnoregulado1, gridBagConstraints);

        jButtonregistrar.setText("Registrar Producto");
        jButtonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 30, 0, 0);
        getContentPane().add(jButtonregistrar, gridBagConstraints);

        jButtonnuevoclient.setText("Nuevo cliente");
        jButtonnuevoclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnuevoclientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 0);
        getContentPane().add(jButtonnuevoclient, gridBagConstraints);

        jButtonfinalizar.setText("Finalizar");
        jButtonfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinalizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 125;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 310;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        getContentPane().add(jButtonfinalizar, gridBagConstraints);

        labeltotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeltotal.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 0, 0);
        getContentPane().add(labeltotal, gridBagConstraints);

        jFormattedTexttotal.setEditable(false);
        jFormattedTexttotal.setBackground(new java.awt.Color(204, 204, 204));
        jFormattedTexttotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 272;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        getContentPane().add(jFormattedTexttotal, gridBagConstraints);

        labeltotalgeneral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeltotalgeneral.setText("Total general:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 30, 29, 0);
        getContentPane().add(labeltotalgeneral, gridBagConstraints);

        jFormattedTexttotalgeneral.setEditable(false);
        jFormattedTexttotalgeneral.setBackground(new java.awt.Color(0, 102, 255));
        jFormattedTexttotalgeneral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 272;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 29, 0);
        getContentPane().add(jFormattedTexttotalgeneral, gridBagConstraints);

        labelnfactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelnfactura.setForeground(new java.awt.Color(255, 0, 0));
        labelnfactura.setText("Nº Factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 88;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 309;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        getContentPane().add(labelnfactura, gridBagConstraints);

        labelnfacturalbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelnfacturalbl.setForeground(new java.awt.Color(255, 0, 0));
        labelnfacturalbl.setText("Nº Factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 49;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(labelnfacturalbl, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBnoregulado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBnoregulado1ActionPerformed
          reguladob =0;
    }//GEN-LAST:event_jRadioBnoregulado1ActionPerformed

    private void jRadioBmedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBmedicamentosActionPerformed
        textproveedor.setEditable(false);
        textproveedor.setBackground(Color.LIGHT_GRAY);
        jFormattedTextfecha.setEditable(true);
        jFormattedTextfecha.setBackground(Color.WHITE);
        textproveedor.setText("");
        jRadioBnoregulado1.setEnabled(true);
        jRadioBregulado.setEnabled(true);
        
        textcodigo.setText("");
        textdescripcion.setText("");
        jFormattedTextcantidad.setText("");
        jFormattedTextcosto.setText("");
        jFormattedTextfecha.setText("");
        textproveedor.setText("");
        
        
    }//GEN-LAST:event_jRadioBmedicamentosActionPerformed

    private void jRadioButilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButilesActionPerformed
       textproveedor.setEditable(true);
       textproveedor.setBackground(Color.WHITE);
       jFormattedTextfecha.setEditable(false);
       jFormattedTextfecha.setBackground(Color.LIGHT_GRAY);
       jFormattedTextfecha.setText("");
       jRadioBnoregulado1.setEnabled(false);
       jRadioBregulado.setEnabled(false);
       
       textcodigo.setText("");
       textdescripcion.setText("");
       jFormattedTextcantidad.setText("");
       jFormattedTextcosto.setText("");
       jFormattedTextfecha.setText("");
       textproveedor.setText("");
    }//GEN-LAST:event_jRadioButilesActionPerformed

    private void textnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnombreKeyTyped
       if (textnombre.getText().length()==20) {
             evt.consume();
             textapellidos.requestFocus();
        } 
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        textapellidos.requestFocus();
        }
    }//GEN-LAST:event_textnombreKeyTyped

    private void jFormattedTextcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextcedulaKeyTyped
       
        if (jFormattedTextcedula.getText().length()==8 ||
                 jFormattedTextcedula.getText().length()>10) {
             evt.consume();
             textnombre.requestFocus();
        } 
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        textnombre.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextcedulaKeyTyped

    private void jFormattedTextcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextcedulaFocusLost
        if (jFormattedTextcedula.getText().isEmpty()){
            
        }
        else{
           if (jFormattedTextcedula.getText().length()<6 || 
                jFormattedTextcedula.getText().length()>10) {
             JOptionPane.showMessageDialog(null, "Ingrese un número de cédula válido",
                     "Validacion de Datos ",JOptionPane.ERROR_MESSAGE);
             jFormattedTextcedula.requestFocus();
            }  
        }
    }//GEN-LAST:event_jFormattedTextcedulaFocusLost

    private void jButtonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarActionPerformed
        String regula2;
        int cant;
        double costo,total;
        if (jRadioBmedicamentos.isSelected()) {
            
            if (jFormattedTextcedula.getText().isEmpty() || textnombre.getText().isEmpty() ||
                textapellidos.getText().isEmpty() || textcodigo.getText().isEmpty()
                || textdescripcion.getText().isEmpty() || jFormattedTextcantidad.getText().isEmpty()
                ||jFormattedTextcosto.getText().isEmpty() || jFormattedTextfecha.getText().isEmpty()){
            
                    JOptionPane.showMessageDialog(null, "Ingrese todos los datos",
                     "Validacion de Datos ",JOptionPane.ERROR_MESSAGE);
                     
        }
            else {
               
               jFormattedTextcedula.setEditable(false);
               jFormattedTextcedula.setBackground(Color.LIGHT_GRAY);
               textnombre.setEditable(false);
               textnombre.setBackground(Color.LIGHT_GRAY);
               textapellidos.setEditable(false);
               textapellidos.setBackground(Color.LIGHT_GRAY);
               medicamentos medicinas = new medicamentos();
               if (reguladob ==0){
                   
                   String costoadouble= jFormattedTextcosto.getText();
                   costoadouble = costoadouble.replace(',', '.');
                   double costoadouble1 = Double.parseDouble(costoadouble);
                   costo = costoadouble1;
                   cant = Integer.parseInt( jFormattedTextcantidad.getText());
                   regula2="No";
                   total=medicinas.medicamentonoregulado(cant, costo);
                   jFormattedTexttotal.setText(Double.toString(total));
                   totalg = ( totalg)+total;
                    totalvendidos++;
                    medvendidos++;
                    mednoreguladosvendidos++;
                    totalgeneralvendido = ( totalgeneralvendido)+total;
                    totalmedvendido = ( totalmedvendido) + total;
                   jFormattedTexttotalgeneral.setText(Double.toString( totalg));
                   
                   String registro = medicinas.Registrarmedicamentos(jFormattedTextcedula.getText()
                       , textnombre.getText(), textapellidos.getText(), textcodigo.getText(),
                       textdescripcion.getText(), jFormattedTextcantidad.getText(), 
                       jFormattedTextcosto.getText(), jFormattedTextfecha.getText(), regula2);
               JOptionPane.showMessageDialog(rootPane, "Factura Nº: "+ labelnfactura.getText()+ 
                       "\n"+registro+"\n"+" Total: "+ total);
               
               textcodigo.setText("");
               textdescripcion.setText("");
               jFormattedTextcantidad.setText("");
               jFormattedTextcosto.setText("");
               jFormattedTextfecha.setText("");
               
                
               
               if (cicliente != jFormattedTextcedula.getText()){
                    totalclientes++;
               }
               cicliente = jFormattedTextcedula.getText();
               
               }
               else{
                   String costoadouble= jFormattedTextcosto.getText();
                   costoadouble = costoadouble.replace(',', '.');
                   double costoadouble1 = Double.parseDouble(costoadouble);
                   costo = costoadouble1;
                   cant = Integer.parseInt( jFormattedTextcantidad.getText());
                   regula2="Si";
                   total=medicinas.medicamentoregulado(cant, costo);
                   jFormattedTexttotal.setText(Double.toString(total));
                    totalg = ( totalg)+total;
                    totalvendidos++;
                    medvendidos++;
                    medreguladosvendidos++;
                    totalgeneralvendido = ( totalgeneralvendido)+total;
                    totalmedvendido = ( totalmedvendido) + total;
                   jFormattedTexttotalgeneral.setText(Double.toString( totalg));
                   
                   String registro = medicinas.Registrarmedicamentos(jFormattedTextcedula.getText()
                       , textnombre.getText(), textapellidos.getText(), textcodigo.getText(),
                       textdescripcion.getText(), jFormattedTextcantidad.getText(), 
                       jFormattedTextcosto.getText(), jFormattedTextfecha.getText(), regula2);
               JOptionPane.showMessageDialog(rootPane, registro+"\n"+" Total: "+ total);
               
               textcodigo.setText("");
               textdescripcion.setText("");
               jFormattedTextcantidad.setText("");
               jFormattedTextcosto.setText("");
               jFormattedTextfecha.setText("");
               
               if (cicliente != jFormattedTextcedula.getText()){
                    totalclientes++;
               }
               cicliente = jFormattedTextcedula.getText();
               }
               
            }
        }
        if (jRadioButiles.isSelected()){
            
            if (jFormattedTextcedula.getText().isEmpty() || textnombre.getText().isEmpty() ||
                textapellidos.getText().isEmpty() || textcodigo.getText().isEmpty()
                || textdescripcion.getText().isEmpty() || jFormattedTextcantidad.getText().isEmpty()
                ||jFormattedTextcosto.getText().isEmpty() || textproveedor.getText().isEmpty()){
                
                JOptionPane.showMessageDialog(null, "Ingrese todos los datos",
                     "Validacion de Datos ",JOptionPane.ERROR_MESSAGE);
                
            }
            
            else {
                
               jFormattedTextcedula.setEditable(false);
               jFormattedTextcedula.setBackground(Color.LIGHT_GRAY);
               textnombre.setEditable(false);
               textnombre.setBackground(Color.LIGHT_GRAY);
               textapellidos.setEditable(false);
               textapellidos.setBackground(Color.LIGHT_GRAY);
               
               utiles utiles = new utiles();
               
               String costoadouble= jFormattedTextcosto.getText();
                   costoadouble = costoadouble.replace(',', '.');
                   double costoadouble1 = Double.parseDouble(costoadouble);
                   costo = costoadouble1;
                   cant = Integer.parseInt( jFormattedTextcantidad.getText());
                   total=utiles.calculoutiles(cant, costo);
                   jFormattedTexttotal.setText(Double.toString(total));
                    totalg = ( totalg)+total;
                    totalvendidos++;
                    utilesvendidos++;
                    totalgeneralvendido = ( totalgeneralvendido) + total;
                    totalutilesvendido = ( totalutilesvendido) + total;
                   jFormattedTexttotalgeneral.setText(Double.toString( totalg));

                   String registro = utiles.Registrarutiles(jFormattedTextcedula.getText()
                       , textnombre.getText(), textapellidos.getText(), textcodigo.getText(),
                       textdescripcion.getText(), jFormattedTextcantidad.getText(), 
                       jFormattedTextcosto.getText(), textproveedor.getText());
               JOptionPane.showMessageDialog(rootPane, registro+"\n"+" Total: "+ total);
               
               textcodigo.setText("");
               textdescripcion.setText("");
               jFormattedTextcantidad.setText("");
               jFormattedTextcosto.setText("");
               textproveedor.setText("");
               
               if (cicliente != jFormattedTextcedula.getText()){
                    totalclientes++;
               }
               cicliente = jFormattedTextcedula.getText();
               
            }
            
        }
        
    }//GEN-LAST:event_jButtonregistrarActionPerformed

    private void jFormattedTextcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextcantidadKeyTyped
        if (jFormattedTextcantidad.getText().length()==2) {
             evt.consume();
             jFormattedTextcosto.requestFocus();
        } 
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        jFormattedTextcosto.requestFocus();
        }
        
    }//GEN-LAST:event_jFormattedTextcantidadKeyTyped

    private void textcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcodigoKeyTyped
       if (textcodigo.getText().length()==5) {
             evt.consume();
        } 
    }//GEN-LAST:event_textcodigoKeyTyped

    private void textapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textapellidosKeyTyped
      if (textapellidos.getText().length()==20) {
             evt.consume();
             textcodigo.requestFocus();
        } 
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        textcodigo.requestFocus();
        }
    }//GEN-LAST:event_textapellidosKeyTyped

    private void textdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textdescripcionKeyTyped
        if (textdescripcion.getText().length()==20) {
             evt.consume();
             jFormattedTextcantidad.requestFocus();
        } 
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        jFormattedTextcantidad.requestFocus();
        }
    }//GEN-LAST:event_textdescripcionKeyTyped

    private void jFormattedTextfechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextfechaKeyTyped
        if (jFormattedTextfecha.getText().length()==10) {
             evt.consume();
        } 
    }//GEN-LAST:event_jFormattedTextfechaKeyTyped

    private void textproveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textproveedorKeyTyped
        if (textproveedor.getText().length()==20) {
             evt.consume();
        } 
    }//GEN-LAST:event_textproveedorKeyTyped

    private void jRadioBreguladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBreguladoActionPerformed
       reguladob =1;
    }//GEN-LAST:event_jRadioBreguladoActionPerformed

    private void jButtonnuevoclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnuevoclientActionPerformed
       
       jFormattedTextcedula.setText(""); 
       textnombre.setText("");
       textapellidos.setText("");
       textcodigo.setText("");
       textdescripcion.setText("");
       jFormattedTextcantidad.setText("");
       jFormattedTextcosto.setText("");
       jFormattedTextfecha.setText("");
       textproveedor.setText("");
       jFormattedTexttotal.setText("");
       jFormattedTexttotalgeneral.setText("");
       
       jRadioBmedicamentos.setSelected(true);
       jRadioBnoregulado1.setSelected(true);
       textproveedor.setEditable(true);
       textproveedor.setBackground(Color.WHITE);
       jFormattedTextfecha.setEditable(false);
       jFormattedTextfecha.setBackground(Color.LIGHT_GRAY);
       jFormattedTextfecha.setText("");
       jRadioBnoregulado1.setEnabled(false);
       jRadioBregulado.setEnabled(false);
       
       jFormattedTextcedula.setEditable(true);
       jFormattedTextcedula.setBackground(Color.WHITE);
       textnombre.setEditable(true);
       textnombre.setBackground(Color.WHITE);
       textapellidos.setEditable(true);
       textapellidos.setBackground(Color.WHITE);
       
        totalg=0;
       reguladob =0;
       labelnfactura.setText(""+rnd.nextInt());
    }//GEN-LAST:event_jButtonnuevoclientActionPerformed

    private void jButtonfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinalizarActionPerformed
       
       jFormattedTextcedula.setText(""); 
       textnombre.setText("");
       textapellidos.setText("");
       textcodigo.setText("");
       textdescripcion.setText("");
       jFormattedTextcantidad.setText("");
       jFormattedTextcosto.setText("");
       jFormattedTextfecha.setText("");
       textproveedor.setText("");
       jFormattedTexttotal.setText("");
       jFormattedTexttotalgeneral.setText("");
       
       
       jRadioBmedicamentos.setSelected(true);
       jRadioBnoregulado1.setSelected(true);
       textproveedor.setEditable(true);
       textproveedor.setBackground(Color.WHITE);
       jFormattedTextfecha.setEditable(false);
       jFormattedTextfecha.setBackground(Color.LIGHT_GRAY);
       jFormattedTextfecha.setText("");
       jRadioBnoregulado1.setEnabled(false);
       jRadioBregulado.setEnabled(false);
       
       jFormattedTextcedula.setEditable(true);
       jFormattedTextcedula.setBackground(Color.WHITE);
       textnombre.setEditable(true);
       textnombre.setBackground(Color.WHITE);
       textapellidos.setEditable(true);
       textapellidos.setBackground(Color.WHITE);
       
        totalg=0;
       reguladob =0;
       
       ventana0 ventana0= new ventana0();
       ventana0.setVisible(true);
       
//       this.setVisible(false);
   this.dispose();
       
    }//GEN-LAST:event_jButtonfinalizarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String registro =  "INFORME GENERAL: "+"\n"+"Productos vendidos: "+ totalvendidos+"\n"+
         "\n"+"Medicamentos vendidos: " +medvendidos+"\n"+"Medicamentos regulados vendidos: "
         +medreguladosvendidos+ "\n"+"Medicamentos no regulados vendidos: "
         +mednoreguladosvendidos+"\n"+ "Venta de medicamentos Bs: "+totalmedvendido+
         "\n"+"Utiles vendidos: " +utilesvendidos+"\n"+"Venta de utiles Bs: "+
         totalutilesvendido+ "\n"+"Total general de ventas Bs: "+totalgeneralvendido
         +"\n"+"Clientes atendidos: " +totalclientes;
               JOptionPane.showMessageDialog(rootPane, registro );
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonfinalizar;
    private javax.swing.JButton jButtonnuevoclient;
    private javax.swing.JButton jButtonregistrar;
    private javax.swing.JFormattedTextField jFormattedTextcantidad;
    private javax.swing.JFormattedTextField jFormattedTextcedula;
    private javax.swing.JFormattedTextField jFormattedTextcosto;
    private javax.swing.JFormattedTextField jFormattedTextfecha;
    private javax.swing.JFormattedTextField jFormattedTexttotal;
    private javax.swing.JFormattedTextField jFormattedTexttotalgeneral;
    private javax.swing.JRadioButton jRadioBmedicamentos;
    private javax.swing.JRadioButton jRadioBnoregulado1;
    private javax.swing.JRadioButton jRadioBregulado;
    private javax.swing.JRadioButton jRadioButiles;
    private javax.swing.JLabel labelapellidos;
    private javax.swing.JLabel labelcantidad;
    private javax.swing.JLabel labelcedula;
    private javax.swing.JLabel labelcliente;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelcosto;
    private javax.swing.JLabel labeldescripcion;
    private javax.swing.JLabel labelfechaexp;
    private javax.swing.JLabel labelnfactura;
    private javax.swing.JLabel labelnfacturalbl;
    private javax.swing.JLabel labelnombrefarmacia;
    private javax.swing.JLabel labelnombres;
    private javax.swing.JLabel labelproducto;
    private javax.swing.JLabel labelproveedor;
    private javax.swing.JLabel labeltotal;
    private javax.swing.JLabel labeltotalgeneral;
    private javax.swing.ButtonGroup producto;
    private javax.swing.ButtonGroup regulado;
    private javax.swing.JTextField textapellidos;
    private javax.swing.JTextField textcodigo;
    private javax.swing.JTextField textdescripcion;
    private javax.swing.JTextField textnombre;
    private javax.swing.JTextField textproveedor;
    // End of variables declaration//GEN-END:variables
}
