/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class ventana0 extends javax.swing.JFrame {

    
    
public double totalg;
public int totalvendidos;
public int medvendidos;
public int medreguladosvendidos;
public int mednoreguladosvendidos;
public int utilesvendidos;
public double totalgeneralvendido;
public double totalmedvendido;
public double totalutilesvendido;
public int totalclientes;

    /**
     * Creates new form ventana0
     */
    public ventana0() {
        initComponents();
        setLocationRelativeTo(null);
        ventana1 cnt = new ventana1(); 
        
 totalg = cnt.totalgeneralvendido;
//        totalvendidos=0;
//        medvendidos=0;
//        medreguladosvendidos=0;
//        mednoreguladosvendidos=0;
//        utilesvendidos=0;
//        totalgeneralvendido=0;
//        totalmedvendido=0;
//        totalutilesvendido=0;
//        totalclientes=0;
        
        
        
    Timer timer = new Timer (1000, new ActionListener ()
{
    public void actionPerformed(ActionEvent e)
    {
       Date fecha = new Date ();
        jLabelfecha.setText(fecha.toLocaleString());
     }
});


timer.start();
    }
 
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelfarmacia = new javax.swing.JLabel();
        jButtonregistroproductos = new javax.swing.JButton();
        jButtonInformederegistros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelfecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 282));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelfarmacia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelfarmacia.setText("Farmacia IUPSM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 92, 0, 0);
        getContentPane().add(jLabelfarmacia, gridBagConstraints);

        jButtonregistroproductos.setText("Registrar productos");
        jButtonregistroproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistroproductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 0);
        getContentPane().add(jButtonregistroproductos, gridBagConstraints);

        jButtonInformederegistros.setText("Informe de Registros");
        jButtonInformederegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformederegistrosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 40, 0, 15);
        getContentPane().add(jButtonInformederegistros, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 112));

        jLabelfecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelfecha.setText("fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelfecha)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelfecha)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 40, 46, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInformederegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformederegistrosActionPerformed
     ventana2 ventana2= new ventana2();
        ventana2.setVisible(true);
        
        JOptionPane.showMessageDialog(rootPane, totalg +  "\n"+totalvendidos+
                medvendidos +totalclientes);
    }//GEN-LAST:event_jButtonInformederegistrosActionPerformed

    private void jButtonregistroproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistroproductosActionPerformed
     ventana1 ventana1= new ventana1();
     ventana1.setVisible(true);
//     this.setVisible(false);
    }//GEN-LAST:event_jButtonregistroproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana0().setVisible(true);
                
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInformederegistros;
    private javax.swing.JButton jButtonregistroproductos;
    private javax.swing.JLabel jLabelfarmacia;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
